name: CarsPlugin
version: ${project.version}
main: com.gmail.anthony17j.carsplugin.CarsPlugin
api-version: 1.17
authors: [ Uxzylon ]
description: Ajoute des voitures
permissions:
  cars.drive.*:
    description: Autorise la conduite
  cars.passenger.*:
    description: Autorise la montee en passager
  cars.command.place:
    description: Autorise fonction place
    children:
      cars.command: true
  cars.command.remove:
    description: Autorise fonction remove
    children:
      cars.command: true
  cars.command.reload:
    description: Autorise la fonction reload
    children:
      cars.command: true
commands:
  cars:
    description: Commande Principale
    usage: /<command> <fonction>
    permission: cars.command