name: CarsPlugin
version: ${project.version}
main: com.gmail.anthony17j.carsplugin.CarsPlugin
api-version: 1.17
authors: [ Uxzylon ]
description: Ajoute des voitures
permissions:
  cars.drive.*:

  cars.passenger.*:

commands:
  cars:
    description: Commande Principale
    usage: /<command> <fonction>
    permission: cars.command